apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ta4t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ta4t
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ta4t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ta4t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ta4t
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bblb-tenant/rhtap-demo-app/hacbs-test-project-ta4t@sha256:fa94d84fa6583baa24fedb60340a5b897fa2e45048b11b6a069aa2fc1cb43c0a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
