apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ta4t
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bblb-tenant/rhtap-demo-app/hacbs-test-project-ta4t@sha256:fe156be059b62c857fe0a012abbc814f5e223fce82eae8139d622de569918ece
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
